
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tf-architect-backend
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend:/app
      - /app/chroma_db_terraform # Persist Vector DB inside container
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: tf-architect-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
